name: Python application workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install spacy
        python -m spacy download en_core_web_sm

    - name: Save spaCy model
      run: |
        mkdir -p ./models/en_core_web_sm
        cp -r $(python -c "import spacy; print(spacy.util.get_package_path('en_core_web_sm'))")/* ./models/en_core_web_sm/

    - name: Run your script
      run: python main.py 

